### ISSUE TITLE
System crashing when applying a theme

### ISSUE THREAD

**Issue by und3cr1pted** [Juanen100/StyleMiiU-Plugin#2]
Whenever I try to apply a theme, the whole system freezes.

**Comment by Juanen100** [comment]
Does that happen with any theme or just with one theme? If it's only with one theme, it is likely too heavy, otherwise it's probably that you don't have ThemeRedirectionModule. I'd recommend redownloading the plugin from the homebrew app store since that should download all dependencies directly

**Comment by und3cr1pted** [comment]
Thanks for the quick answer. The crashes unfortunately happened with every theme, but I'll check if I installed everything correctly

**Comment by Juanen100** [comment]
Yeah, sdcafiine fights with the plugin, sometime it get's stuck in limbo and another time it overrides the other plugin, just removing the wii u menu modpack should be enough

**Comment by und3cr1pted** [comment]
Okay, thank you

**Comment by RedBean3ll** [comment]
Hello. I'm having the same issue. I've modded my Wii U recently. StyleMiiU was installed over the HB App Store. I've checked my SD Card and ThemeRedirectionModule is in place and sdcafiine is not installed. Themes are where they should be. Booting the Wii U starts with the first theme. However, any attempts to select a theme manually causes a crash. Both themes are tested and not too big. This issue happens when selecting any theme. Including the proven functional themes. I wanted to bring this up because this is a great plugin. I really like it. However, I would like to make sure you're aware of it so it can be fixed.

**Comment by Juanen100** [comment]
That's odd, I'll check and see if I can recreate the issue

**Comment by Juanen100** [comment]
I believe it has been fixed, I'll push an update in a moment, whenever you can test it to see if it ever happens

**Comment by und3cr1pted** [comment]
Sounds good. I'll be ready to test the update :)

**Comment by Juanen100** [comment]
You can now, it's update 0.4.1

**Comment by RedBean3ll** [comment]
Transition appears to start but still crashes. Give me a moment to see if I can figure out setting up debugging so I can look at the logs and share them.

**Comment by RedBean3ll** [comment]
Ok. I found two debugging methods. One requires a cable and setup I can't quickly produce on the fly and the other appears to be used with the Home Brew browser used in Tiramisu which adds a new set of variables. The best I can do is share a link to the themes I'm using and give a list of plugins, modules, and Apps. In the meantime, I'm going to take a quick look at the codebase. If you have any more questions or any debugging tips, I am open to giving it a shot. 

Modules:
- setup
- AromaBaseModule.wms
- ContentRedirectionModule.wms
- CURLWrapperModule.wms
- FunctionPatcherModule.wms
- KernelModule.wms
- MemoryMappingModule.wms
- NotificationModule.wms
- PatchMemoryRelocationsModule.wms
- PluginBackend.wms
- RPXLoadingModule.wms
- SDHotSwapModule.wms
- ThemeRedirectionModule.wms
- WUHBUtilsModule.wms

Plugins:
- config/..
- AromaBasePlugin.wps
- drc_region_free.wps
- ftpiiu.wps
- homebrew_on_menu.wps
- Inkay-pretendo.wps
- regionfree.wps
- screenshot.wps
- stylemiiu.wps

Apps:
- appstore/..
- AromaUpdater/..
- Koopair/..
- save/..
- SaveMiiModWUTPort/..
- WiiU-Shell/..
- wiiuident/..
- wudd
- wup_installer_gx2/..
- PayloadLoaderInstaller.wuhb

Link to theme 1# - Peaceful Koi:
https://drive.google.com/file/d/1Q2OcvhXqSQJ6xsZR2jZ2S0283xKYH9Fy/view

Link to theme 2# - Hatsune Miku:
https://github.com/81m1tr1/WiiU-Menu-Themes/releases/tag/v.2.0.0

**Comment by Dantendo09** [comment]
I'm also here to tell that the console still crashes on the newest Version.

**Comment by Juanen100** [comment]
This is so incredibly weird, I tried both themes you said but they work correctly under my wii u, could it be a wrong ThemeRedirectionModule wms file has been pushed to the repo? I'll try downloading it from the hb app store to see

**Comment by Juanen100** [comment]
If anyone could provide me a video of what happens to get a better idea of what's the issue I'll be really thankful

**Comment by Dantendo09** [comment]
I don't habe time to make a video but I can describe it:
First I opened up the Plugin menu
Then I went to the StyleMiiU plugin and checked if it's enabled.
After that I went to available themes.
When I selected a theme the console crashed with this sound. And it happened directly after pressing A to choose a theme.

**Comment by und3cr1pted** [comment]
I'll make a video and paste the YouTube link along with some screenshots in another comment

**Comment by Juanen100** [comment]
Alr, thanks

**Comment by und3cr1pted** [comment]
Hope the video quality is good enough xD

![Image](https://github.com/user-attachments/assets/1f16dd95-7d90-4b65-a44d-0858484ce452)
![Image](https://github.com/user-attachments/assets/9c3ab59d-f53c-4b25-a957-1fa530838fad)

Video: https://www.youtube.com/watch?v=rqmM5ukIP6s

**Comment by Juanen100** [comment]
Oh I think I know how to trigger the bug now, I'll try and see if I can make a fix

**Comment by und3cr1pted** [comment]
Okay, I'm happy to be able to help with this issue. I've started to learn Java in a while ago and understand how difficult troubleshooting can be :P

**Comment by Juanen100** [comment]
I think I've fixed the plugin, could someone test this version to see if it's fixed

[stylemiiu.zip](https://github.com/user-attachments/files/18629420/stylemiiu.zip)

**Comment by und3cr1pted** [comment]
Okay, I'll try the update

**Comment by und3cr1pted** [comment]
I can also confirm that the Wii U doesn't crash anymore when selecting a theme, but it doesn't seem to apply the theme when after the Wii U restarts.

Could you send me a copy of your themes and where you stored them on the SD card?

**Comment by Juanen100** [comment]
Check if the Enabled StyleMiiU option is disabled, I disabled it if no theme is selected since it causes a bootloop

**Comment by und3cr1pted** [comment]
![Image](https://github.com/user-attachments/assets/668d1e9d-f210-4aaf-a1aa-cf37b593bce9) 

Can I put the Men and Men2 files into a folder like this?

**Comment by Juanen100** [comment]
Yeah, they should work correctly

**Comment by Juanen100** [comment]
Ok, the bootloop no longer happens if no theme is selected in the menu, so that's another thing fixed

**Comment by RedBean3ll** [comment]
Hey! Now you got it!! Congratulations. I wish I could have been of help, but I've been busy. Latest version is tested. Behavior has changed to not reloading the Wii U home screen until you close the WII U Plugin Menu. Manually selecting a theme does not crash the WII U anymore. Enabling|Disabling shuffle forces a reload on close. As far as I can see, this Bug story is closed.

**Comment by Juanen100** [comment]
Awesome, will release the hotfix in a sec and glad I've fixed all bugs

**Comment by Juanen100** [comment]
I cannot stress how many times I've been debugging with the NotificationModule and just trying to see whatever it goes through and this time it was just pure guessing since I had a pretty good idea of what could be the cause of it

**Comment by RedBean3ll** [comment]
> I cannot stress how many times I've been debugging with the NotificationModule and just trying to see whatever it goes through and this time it was just pure guessing since I had a pretty good idea of what could be the cause of it

I'm assuming with the WII U is when it crashes, it crashes, and without an external debugging tool, there is no guarantee you can save logs to the SD Card when it crashes like this. I'm glad your hunch was correct.

**Comment by RedBean3ll** [comment]
> ![Image](https://github.com/user-attachments/assets/668d1e9d-f210-4aaf-a1aa-cf37b593bce9)
> 
> Can I put the Men and Men2 files into a folder like this?

Yes. That will work.
